const INITIAL_PLANS = [
  {
    id: "tech_python_01",
    title: "Python Zero to Hero",
    description: "A complete roadmap to mastering Python.",
    progress: 45,
    category: "Technology",
    difficulty: "Hard",
    duration: "8 Weeks",
    rating: 4.9,
    isFavorite: false,
    tags: ["Coding", "Backend"],
    tasks: [
      {
        id: "p1",
        title: "Setup & Variables",
        completed: true,
        notes: "Install Python and VS Code. Learn str, int, float.",
        time: "45 min",
        type: "video",
        resources: {
          youtube: "https://youtu.be/_uQrJ0TkZlc",
          article: "https://realpython.com/python-variables/",
        },
        customResources: [],
      },
      {
        id: "p2",
        title: "Control Flow Logic",
        completed: false,
        notes: "Mastering If, Else, and Elif statements.",
        time: "30 min",
        type: "practice",
        resources: {
          practice: "https://www.hackerrank.com/domains/python",
        },
        customResources: [],
      },
      {
        id: "p3",
        title: "Lists & Dictionaries",
        completed: false,
        notes: "Understanding data structures is key.",
        time: "60 min",
        type: "read",
        resources: {
          article: "https://docs.python.org/3/tutorial/datastructures.html",
        },
        customResources: [],
      },
    ],
  },
  {
    id: "health_fit_01",
    title: "Home Bodyweight Shred",
    description: "No equipment needed. Build muscle and lose fat.",
    progress: 20,
    category: "Health",
    difficulty: "Medium",
    duration: "6 Weeks",
    rating: 4.7,
    isFavorite: true,
    tags: ["Fitness", "Strength"],
    tasks: [
      {
        id: "w1",
        title: "Dynamic Warmup",
        completed: true,
        notes: "Never skip this. Neck circles, arm swings.",
        time: "10 min",
        type: "video",
        resources: {
          youtube: "https://youtu.be/uNILuHVUsAME",
        },
        customResources: [],
      },
      {
        id: "w2",
        title: "Push-up Progression",
        completed: false,
        notes: "3 sets of 12 reps. Use knees if needed.",
        time: "15 min",
        type: "practice",
        resources: {
          article: "https://www.nerdfitness.com/blog/proper-push-up/",
        },
        customResources: [],
      },
    ],
  },
];